OUTNAME_RELEASE = sample_dynamic_reshape_r
OUTNAME_DEBUG   = sample_dynamic_reshape_debug_r
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
