OUTNAME_RELEASE = sample_onnx_resnet50_r
OUTNAME_DEBUG   = sample_onnx_resnet50_debug_r
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
