OUTNAME_RELEASE = sample_implicit_int8_ptq
OUTNAME_DEBUG   = sample_implicit_int8_ptq_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
